# loaded when no context is specified
[deploy]
memory = 256

# loaded when the dev profile is selected
[dev.deploy]
memory = 256

# loaded when the staging profile is selected
[staging.deploy]
memory = 256

# loaded when the production profile is selected
[production.deploy]
memory = 256